import type { CSSProperties } from "react";

const PALETTE = {
  background: "#f7f8fb",
  surface: "#ffffff",
  footer: "#160b30",
  brand: "#6f3ff5",
  brandStrong: "#5f2eea",
  brandSoft: "#f2e8ff",
  text: "#425069",
  textMuted: "#7a8598",
  textSoft: "#a7b1c2",
  border: "#e5e8ef",
  success: "#2fc160",
  danger: "#ff6b6b",
} as const;

export const THEME_VARS = {
  "--color-background": PALETTE.background,
  "--color-foreground": PALETTE.text,
  "--color-footer": PALETTE.footer,
  "--color-brand-start": PALETTE.brandStrong,
  "--color-brand-end": PALETTE.brand,
  "--color-brand-primary": PALETTE.brand,
  "--color-brand-strong": PALETTE.brandStrong,
  "--color-brand-border": PALETTE.brand,
  "--color-brand-text": PALETTE.brand,
  "--color-brand-focus": PALETTE.brand,
  "--color-brand-hover": PALETTE.brandSoft,
  "--color-brand-surface": PALETTE.brandSoft,
  "--color-brand-search-border": PALETTE.brandSoft,
  "--color-brand-search-focus": PALETTE.brand,
  "--color-brand-search-icon": PALETTE.brand,
  "--color-text-heading": PALETTE.text,
  "--color-text-primary": PALETTE.text,
  "--color-text-secondary": PALETTE.text,
  "--color-text-body": PALETTE.text,
  "--color-text-muted": PALETTE.textMuted,
  "--color-text-subtle": PALETTE.textMuted,
  "--color-text-label": PALETTE.text,
  "--color-text-control": PALETTE.text,
  "--color-text-toolbar": PALETTE.text,
  "--color-text-toolbar-muted": PALETTE.textMuted,
  "--color-text-interactive": PALETTE.text,
  "--color-text-dark": PALETTE.text,
  "--color-text-neutral": PALETTE.text,
  "--color-text-page-number": PALETTE.text,
  "--color-text-caption": PALETTE.textMuted,
  "--color-text-error": PALETTE.danger,
  "--color-placeholder": PALETTE.textSoft,
  "--color-placeholder-soft": PALETTE.textSoft,
  "--color-icon-muted": PALETTE.textSoft,
  "--color-icon-soft": PALETTE.textSoft,
  "--color-icon-disabled": PALETTE.textSoft,
  "--color-icon-light": PALETTE.textSoft,
  "--color-icon-choice": PALETTE.textSoft,
  "--color-icon-eye": PALETTE.textSoft,
  "--color-border-primary": PALETTE.border,
  "--color-border-secondary": PALETTE.border,
  "--color-border-card": PALETTE.border,
  "--color-border-soft": PALETTE.border,
  "--color-border-login-card": PALETTE.border,
  "--color-border-header": PALETTE.border,
  "--color-border-pager": PALETTE.border,
  "--color-border-login": PALETTE.border,
  "--color-border-option": PALETTE.border,
  "--color-border-question": PALETTE.border,
  "--color-border-score": PALETTE.border,
  "--color-border-editor": PALETTE.border,
  "--color-border-brand-strong": PALETTE.brand,
  "--color-border-empty": PALETTE.border,
  "--color-step-pending": PALETTE.border,
  "--color-hover-surface": PALETTE.background,
  "--color-avatar-surface": PALETTE.border,
  "--color-success": PALETTE.success,
  "--color-success-surface": PALETTE.background,
  "--color-danger-soft": PALETTE.danger,
  "--color-error": PALETTE.danger,
  "--color-label-login": PALETTE.text,
  "--color-overlay": "rgba(45,51,64,0.42)",
  "--gradient-brand": `linear-gradient(90deg, ${PALETTE.brandStrong} 0%, ${PALETTE.brand} 100%)`,
  "--shadow-card": "0 .375rem 1.375rem rgba(15,23,42,0.04)",
  "--shadow-subtle": "0 .25rem 1.125rem rgba(15,23,42,0.04)",
  "--shadow-popover": "0 1.125rem 3rem rgba(15,23,42,0.12)",
  "--shadow-modal": "0 1.5rem 4rem rgba(15,23,42,0.22)",
  "--shadow-brand": "0 .75rem 1.5rem rgba(95,46,234,0.18)",
  "--shadow-brand-strong": "0 .75rem 1.875rem rgba(95,46,234,0.22)",
  "--shadow-search": "0 .125rem .5rem rgba(123,63,246,0.14)",
  "--color-search-spark-start": PALETTE.brandStrong,
  "--color-search-spark-end": PALETTE.brand,
  "--color-search-star-start": PALETTE.brandStrong,
  "--color-search-star-end": PALETTE.brand,
} as CSSProperties;
